project:
  type: website
  output-dir: docs

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: CV
      - href: posts.qmd
        text: Blog
    right: 
      - href: contact.qmd
        text: "{{< fa envelope >}}"

      
format:
  html:
    theme: default
    fontawesome: true
    css: styles.css
    toc: true

editor: visual

